### ISSUE TITLE
should refactor the validators hack for table schema url format fields

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/datapackage-php#14]
there is a problem with the json schema validator and the handling of file paths in the resources data property.

* the data field is defined as array of strings with url format
* however, datapackages allow relative file names
* the json schema validator identifies it as a validation error

currently it was fixed with a simple hack that prepends file:// to the data field

need to review and look for possible problems with this hack, then fix it properly

also, it should really be inside the datapackage class to allow extensibility

**Comment by OriHoch** [comment]
this problem was introduced in #13

**Comment by pwalsh** [comment]
@OriHoch is this still a problem with the latest spec changes (rc2)? cc @roll

**Comment by OriHoch** [comment]
this is still a problem, I opened a PR on specs:
https://github.com/frictionlessdata/specs/pull/480

**Comment by OriHoch** [comment]
fixed in [v0.1.4](https://github.com/frictionlessdata/datapackage-php/releases) - removed the hack as it's not neccessary for latest spes
