### ISSUE TITLE
"path" can be a string or arrray

### ISSUE THREAD

**Issue by dsantuc** [frictionlessdata/datapackage-php#27]
According to the Data Resource spec, the "path" property can be a string or an array of strings:

http://specs.frictionlessdata.io/data-resource/#path-data-in-files

but your code assumes it's an array (e.g. /src/Validators/DatapackageValidator.php:32, /src/Validators/ResourceValidator.php:47).

**Comment by OriHoch** [comment]
thanks! :+1:  
the specs kept changing while I was writing this library..

**Comment by dsantuc** [comment]
I took a stab at it: #28

**Comment by OriHoch** [comment]
thanks, merged to [draft releast v0.1.5](https://github.com/frictionlessdata/datapackage-php/releases)

let me know if you want to test it or if I should just publish it

once it's published it will be available via packagist

**Comment by dsantuc** [comment]
I think it's ok to go.

**Comment by OriHoch** [comment]
published
https://packagist.org/packages/frictionlessdata/datapackage#v0.1.5
