### ISSUE TITLE
Methods to add/remove package resources naming

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-php#30]
# Overview

Across implementations we use:
- `resource.get_resource`
- `resource.add_resource`
- `resource.remove_resource`

But in this package:
- `resource.resource`
- `resource.resource(+descr)`
- `resource.delete_resource`

Not vital but could be confusing for people coming from PY/JS tutorials.

**Comment by OriHoch** [comment]
fixed in 3c3b4126b7aa8b7edd8a66b89bb5ae124ae7b088
