### ISSUE TITLE
Upgrade zippy dependency

### ISSUE THREAD

**Issue by aphofstede** [frictionlessdata/datapackage-php#39]
The zippy version in composer.json is quite old, was there a reason for this or can it be bumped to a 
version that supports Symfony 4? (alchemy/zippy ~0.4.9 afaics)

See:
https://github.com/alchemy-fr/Zippy/commit/bd83a226e2b360ec5737ffa85f0f31fdc3f87531

**Comment by aphofstede** [comment]
Looks like there's still some issues with it: https://github.com/alchemy-fr/Zippy/issues/142

**Comment by OriHoch** [comment]
thanks
