### ISSUE TITLE
Saving a datapackage does not point "path" to the new local resource

### ISSUE THREAD

**Issue by jonrmitchell** [frictionlessdata/datapackage-php#41]
### Steps to reproduce:

```
//create example csv
file_put_contents('/tmp/example.csv', "name,email\nJohn Doe,john@example.com");

//create a new datapackage object
$package = Package::create(['name' => 'csv-example','profile' => 'tabular-data-package']);

//add a csv file
$package->addResource('example.csv',[
    "profile" => "tabular-data-resource",
    "schema" => ["fields" => [["name" => "name", "type" => "string"],["name" => "email", "type" => "string"]]],
    "path" => '/tmp/example.csv'
]);

//save the datapackage
if (is_file('datapackage.zip')) unlink('datapackage.zip');
$package->save("datapackage.zip");

//delete example csv
unlink('/tmp/example.csv');

//load the new package
$package2 = Package::load('datapackage.zip');
```

### Expected result: 
"path" in descriptor file should point to csv in datapackage zip and package should load.

### Actual result:
"path" points to /tmp/example.csv and Package::load throws exception:

> DatapackageValidationFailedException: Datapackage validation failed: data source file does not exist or is not readable: /tmp/example.csv

**Comment by DiegoPino** [comment]
Solved via https://github.com/frictionlessdata/datapackage-php/commit/b60bd4e784ab68a5fc18dd791adb715160d2dd21 by @jonrmitchell. Thank you for your contribution!
