### ISSUE TITLE
Release date of 0.2?

### ISSUE THREAD

**Issue by DiegoPino** [frictionlessdata/datapackage-php#43]
Hi,
I would love to know if a new 0.x release is planned soon. Since the replacement of alchemy/zippy a few months ago (very welcomed) we are now able to deploy it on a newer Symfony 3 project environment where the 0.3.5 restriction of that package was conflicting with our need for 0.4.3. It would be great if we could target a specific version of datapackage-php via `composer require` instead of going for `dev-master` and a hash to have that change applied. 

Thanks a lot

**Comment by roll** [comment]
@OriHoch 
Could you please take a look

**Comment by lwinfree** [comment]
Hi @DiegoPino! We're trying to get all these libraries to a 1.0.0 version release. What do you think about naming the next release V1 instead of 0.2? We think it makes sense, but I wanted to see what you think?

**Comment by DiegoPino** [comment]
@lwinfree I agree. Moving to 0.2 will bring us to 1.0.0 in year 2035. As you noticed i have some pending work to do here and day job has kept me too busy.Its not big really since the code works well. Mostly on the automated testing environment and bring some tests in pair/shape with the rest of the environment. Added a double reminder for me 🤦  and will put some time aside to get it done during the weekend. Thanks for the nudge!

**Comment by lwinfree** [comment]
Thanks @DiegoPino! Please let me or @roll know if you need a hand! :-)

**Comment by DiegoPino** [comment]
@lwinfree thanks! Will try to avoid some shame and get it done asap.

**Comment by DiegoPino** [comment]
Thanks everyone. With tableschema-php updated we have a release too here.
https://github.com/frictionlessdata/datapackage-php/releases/tag/v1.0.0

Closing this one since v0.2 is past.
