### ISSUE TITLE
Travis builds fail for PHP@nightly

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-php#44]
# Overview

Hi, it seems there is a problem on Travis with PHP@nightly for both libs:
- https://travis-ci.org/frictionlessdata/tableschema-php/jobs/594457535
- https://travis-ci.org/frictionlessdata/datapackage-php/jobs/594457547

---

Please preserve this line to notify the @frictionlessdata/php team

**Comment by roll** [comment]
@OriHoch 
Could you please take a look if you can? Maybe just removing `php@nightly` from testing?

**Comment by OriHoch** [comment]
:+1: fixed
https://travis-ci.org/frictionlessdata/tableschema-php/builds/594800534
https://travis-ci.org/frictionlessdata/datapackage-php/builds/594801626

**Comment by roll** [comment]
Thanks!
