### ISSUE TITLE
Is this package being maintained and if so, are you receiving pull requests?

### ISSUE THREAD

**Issue by DiegoPino** [frictionlessdata/datapackage-php#47]
# Overview

Hi, we are using your library core in our Repository system( https://github.com/esmero/strawberryfield) but are getting now conflict because of some deprecated dependencies, in specific the not maintained (archived) anymore `chumper/zipper`. And we need to update/improve some other parts that can not because of the locked versions:

- chumper/zipper uses illuminate/support 5.x and that one  nesbot/carbon ^1.24.1 which is deprecated.

If you are received pulls, can totally refactor these deprecated needs, fix and make a pull to update this wonderful library? Thanks a lot!

Please preserve this line to notify @OriHoch (lead of this repository)

**Comment by OriHoch** [comment]
Hi, I'm happy to hear you are using this package

I'm not actively maintaining it, but I will review and merge this PR

If you want you are welcome to take over maintenance of this package

**Comment by DiegoPino** [comment]
@OriHoch thanks a lot for your quick reply. Will prepare the code, do some tests and build a pull in the next few days. If you like my code and you feel comfortable so, I would love to keep maintaining this package or co-maintain if that is better for you. Thanks again!

**Comment by DiegoPino** [comment]
@OriHoch a first pass can be seen at #48. Happy to make it better and match your expectations. Tests are passing but of course human integration/use may be different. Thanks again!

**Comment by OriHoch** [comment]
@DiegoPino thanks a lot for helping maintain the repository!
I added you as admin of the repository - this should give you permission to publish releases on packagist, the release process is documented in CONTRIBUTING.md
