### ISSUE TITLE
Migrate to Github Actions?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-php#50]
# Overview

We migrated Frictionless-py to Github Actions as Travis CI seems to be dying. Github Actions has been really great so far and simple to migrate to.

**Comment by OriHoch** [comment]
yes, I migrated most of my projects to actions, I'm very pleased with it. Also Travis seems to have a lot of problems where jobs are queued for a long time..

**Comment by DiegoPino** [comment]
@roll and @OriHoch, totally agree. Will look into this for v0.2

**Comment by DiegoPino** [comment]
@roll closing this as done. Tests are passing text matrix is against lower an upper bounds. Once we go PHP 8 we will have of course a third one.

**Comment by roll** [comment]
Great! Thanks!
