### ISSUE TITLE
Rename Master to Main

### ISSUE THREAD

**Issue by DiegoPino** [frictionlessdata/datapackage-php#53]
# Overview

To follow this project's guidelines https://github.com/frictionlessdata/project/issues/537 we are moving away from Master into Main for the base branch. If you are running local fork and please update

git branch -m master main
git fetch origin
git branch -u origin/main main

---

Please preserve this line to notify @DiegoPino (lead of this repository)

**Comment by DiegoPino** [comment]
@roll this may affect some wild usages since many were already to running old-ish release. Should we keep `master` around for a month or so but not as principal and locked/stale? I need to also update the ci.yml again once this happens.

**Comment by DiegoPino** [comment]
@lwinfree tagging you too since you are leading frictionlessdata/project#537 (sorry I just noticed it!)

**Comment by roll** [comment]
@DiegoPino 
Github redirects from master branch to main after renaming so in all the repos we did the change, it went perfectly flawless. The only thing to change manually - local git remotes but there will be a note on Github for contributors.

**Comment by lwinfree** [comment]
thanks @DiegoPino! As roll says, github should automatically redirect any old master branches to main, so you should be OK to implement this change!

**Comment by roll** [comment]
The setting to change it is here - https://github.com/frictionlessdata/datapackage-php/settings/branches

**Comment by DiegoPino** [comment]
Yep. Done. FYI Github actions do not update automatically so committed that. Closing this as solved. Thanks both
